# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
DEFAULT_BRANCH: main # Usually master or main
ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
  - MARKDOWN
  - TERRAFORM
  - CREDENTIALS
  - GIT
#ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
#  - TERRAFORM_TFLINT
#  - TERRAFORM_TERRASCAN
#  - TERRAFORM_TERRAGRUNT
#  - TERRAFORM_TERRAFORM_FMT
#  - TERRAFORM_CHECKOV
#  - CREDENTIALS_SECRETLINT
#DISABLE:
#  - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
#  - SPELL # Uncomment to disable checks of spelling mistakes
DISABLE_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: true

# Mega linter issues are treated as warnings
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
COPYPASTE_JSCPD_DISABLE_ERRORS: true
TERRAFORM_TERRASCAN_DISABLE_ERRORS: true

# Terrascan configuration
TERRAFORM_TERRASCAN_ARGUMENTS: "--config-path .github/linters/terrascan_config.toml"
# https://github.com/accurics/terrascan/blob/master/docs/policies/aws.md